<?php
	include_once(SITE_PATH."framework/core/clientside/javascript/javascript.php");
	include_once(SITE_PATH."framework/core/clientside/javascript/ajax.php");
	include_once(SITE_PATH."framework/core/clientside/globalAttr.php");
	include_once(SITE_PATH."framework/core/clientside/form/form.php");
	include_once(SITE_PATH."framework/core/clientside/form/input.php");
	include_once(SITE_PATH."framework/core/clientside/form/date_time.php");
	include_once(SITE_PATH."framework/core/clientside/form/select.php");
	include_once(SITE_PATH."framework/core/clientside/form/textarea.php");
	include_once(SITE_PATH."framework/core/clientside/form/checkbox.php");
	include_once(SITE_PATH."framework/core/clientside/form/radiobutton.php");
	include_once(SITE_PATH."framework/core/clientside/form/progressbar.php");
	include_once(SITE_PATH."framework/core/clientside/form/file.php");
	include_once(SITE_PATH."framework/core/clientside/form/button.php");
	include_once(SITE_PATH."framework/core/clientside/form/captcha.php");
	include_once(SITE_PATH."framework/core/clientside/form/lookup.php");
	include_once(SITE_PATH."framework/core/clientside/datagrid/datagrid.php");
	include_once(SITE_PATH."framework/core/clientside/dataview/dataview.php");
	
	include_once(SITE_PATH."framework/core/clientside/page.php");
	include_once(SITE_PATH."framework/core/clientside/link.php");
?>